// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy1q7zEx-urpRO88jAkLO49hqRYA7HBu8',
    appId: '1:960742807974:android:edadd0d6c207a540969767',
    messagingSenderId: '960742807974',
    projectId: 'bitsfeeds-fbb1d',
    databaseURL: 'https://bitsfeeds-fbb1d-default-rtdb.firebaseio.com',
    storageBucket: 'bitsfeeds-fbb1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvTtx0Pyk2UuJ8St44c-d6O_azCgPv0yE',
    appId: '1:960742807974:ios:b876822aa7daff18969767',
    messagingSenderId: '960742807974',
    projectId: 'bitsfeeds-fbb1d',
    databaseURL: 'https://bitsfeeds-fbb1d-default-rtdb.firebaseio.com',
    storageBucket: 'bitsfeeds-fbb1d.appspot.com',
    androidClientId: '960742807974-f11q2qej19hcngks05h7gc4bu92nknjh.apps.googleusercontent.com',
    iosClientId: '960742807974-mt6dgk6sp3oqcabqbk8bvgufncadrbmc.apps.googleusercontent.com',
    iosBundleId: 'ajay.com.authFlow',
  );
}
